### ISSUE TITLE
How to make sure, if a task can't be queued, because queue is full?

### ISSUE THREAD

**Issue by animir** [fent/timequeue.js#13]
Looks like it isn't possible?
index.js line 47
`    if (this.maxQueued === this.queued) {
      return;
    }
`

**Comment by fent** [comment]
You can either listen for the `full` event, or check if `queue.intransit === queue.concurrency`

```js
queue.on('full', () => {
  // queue is full
});
```

**Comment by animir** [comment]
@fent thanks
Is it possible to get error in callback of `push`?

**Comment by fent** [comment]
Yep, there is an example in the readme

```js
q.push(2, 2, (err) => {
  // task finished
});
```

**Comment by animir** [comment]
@fent 
Is that callback launched with error, when a task can't be queued, because of maxQueued reached?

**Comment by fent** [comment]
Oh, you mean a full queue because of `maxQueued`. In that case, like in your first message, you can check for `q.maxQueued === q.queued`. And using `q.push()` when a queue is full will not throw.

**Comment by animir** [comment]
@fent I see, thanks. 
I believe, it'd be useful behaviour.
